name: Run tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PORT: ${{ secrets.PORT }}
      HOST: ${{ secrets.HOST }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Build Backend
        run: |
          cd backend
          sudo npm install -g typescript
          npm run build

      - name: Start Backend Server
        run: |
          cd backend
          npm start &
          
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

      - name: Run Backend Tests
        run: |
          npm run test
